### ISSUE TITLE
Visual mode is slow with syntax highlighting enabled

### ISSUE THREAD

**Issue by EtiamNullam** [nacro90/numb.nvim#23] opened 2021-11-20 20:01 UTC
Recently I noticed my neovim become slow when moving around in visual mode. After looking around and bisecting my plugin configuration I narrowed it down to this plugin. I found its best to judge by holding `%` at brace of a somewhat big method.

Minimal config using `vim-plug` (`only-numb.vimrc`):

```viml
call plug#begin('~/.vim-plug')

  Plug 'nacro90/numb.nvim'

call plug#end()

lua << EOF
  require('numb').setup()
EOF
```

Steps to reproduce:
1. Make sure plugin is installed with `:PlugInstall`
2.  Open file of with big method that is syntax highlighted (~60 lines is enough): `nvim -u only-numb.vimrc file-with-big-method.lua`
3. Navigate to brace with `/{<CR>`.
4. Enter visual mode `v`.
5. Hold `%` for 10 seconds.
6. Notice nvim is still locked and will proceed to execute `%` for about 4 more seconds, while without `numb` it will end doing so in less than a second.

Obviously it depends on your machine and maybe how heavy is the syntax. This performance hit is much more visible when you have more plugins. Seems like its gone with `syntax off`.

NVIM v0.6.0-dev+600-gf71be1f87
Windows 10 x64

Its the same with nvim v0.5.1

My key repeat speed is on fastest setting in `Control Panel`.

**Comment by nacro90** [comment] 2023-03-04 19:29
I could not reproduce this bug. I am closing this issue for now

**Closed as not planned by nacro90** 2023-03-04 19:29 UTC
